export const EXCHANGE_RATE_CHANGE_COLOR = {
  increase: "#08a529",
  decrease: "#ff0000",
};

export const EXCHANGE_RATES_EN_NAMES: { [key: string]: string } = {
  "Австралийский доллар": "Australian Dollar",
  "Азербайджанский манат": "Azerbaijaian Mamat",
  "Фунт стерлингов Соединенного королевства": "Pound Sterling",
  "Армянских драмов": "Armenian Dram",
  "Белорусский рубль": "Belarussian Rubble",
  "Болгарский лев": "Bulgarian Lev",
  "Бразильский реал": "Brazilian Real",
  "Венгерских форинтов": "Forint",
  "Гонконгских долларов": "Hond Kong Dollar",
  "Датских крон": "Danish Krone",
  "Доллар США": "US Dollar",
  Евро: "Euro",
  "Индийских рупий": "Indian Rupee",
  "Казахстанских тенге": "Tenge",
  "Канадский доллар": "Canadian Dollar",
  "Киргизских сомов": "Som",
  "Китайских юаней": "Chinese yuan",
  "Молдавских леев": "Moldovan Leu",
  "Норвежских крон": "Norwegean Krone",
  "Польский злотый": "Zloty",
  "Румынский лей": "Romanian Leu",
  "СДР (специальные права заимствования)": "Special drawing rights",
  "Сингапурский доллар": "Singapore Dollar",
  "Таджикских сомони": "Somoni",
  "Турецких лир": "Turkish Lira",
  "Новый туркменский манат": "Turkmenistan new Manat",
  "Узбекских сумов": "Uzbekistan Sum",
  "Украинских гривен": "Hryvnia",
  "Чешских крон": "Czech Koruna",
  "Шведских крон": "Swedish Krona",
  "Швейцарский франк": "Swiss Frank",
  "Южноафриканских рэндов": "South African rand",
  "Вон Республики Корея": "Won",
  "Японских иен": "Yen",
};
